# Generated by Django 5.2.2 on 2026-02-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('password', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('is_approved', models.CharField(max_length=1000)),
                ('is_blocked', models.CharField(max_length=1000)),
                ('status', models.CharField(default='approve', max_length=20)),
                ('profile_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('monthlyamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_number', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Loantable',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('monthlyamount', models.IntegerField()),
                ('loan_details', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('pan_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_reason', models.TextField(blank=True, null=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
