# Generated by Django 6.0.1 on 2026-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_pan_card_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantable',
            name='asset_gold_proof_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_gold_purity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_gold_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_gold_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_home_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_home_proof_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_home_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='asset_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='eligibility_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_employer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_employment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_income_proof_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_pan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_relationship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loantable',
            name='guarantor_years_employment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_employer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_employment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_proof_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='income_years_employment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loantable',
            name='loan_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loantable',
            name='offline_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loantable',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='risk_score',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loantable',
            name='surety_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
