# Generated by Django 6.0.1 on 2026-02-06 10:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_loantable_asset_gold_proof_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantable',
            name='status',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('Pending', 'Pending'),
                    ('Approved', 'Approved'),
                    ('Rejected', 'Rejected'),
                    ('Active', 'Active'),
                    ('Inactive', 'Inactive'),
                ],
            ),
        ),
    ]
