# Generated by Django 6.0.1 on 2026-02-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_loantable_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantable',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='paid_installments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loantable',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loantable',
            name='total_installments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loantable',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loantable',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loantable',
            name='total_repayable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.loantable'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loantable',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
