# Generated by Django 6.0.1 on 2026-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantable',
            name='equipment_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loantable',
            name='equipment_proof_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loantable',
            name='equipment_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loantable',
            name='equipment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loantable',
            name='farmer_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
