# Generated by Django 6.0.1 on 2026-02-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emaillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
